version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '7432:${POSTGRES_PORT}'
    restart: unless-stopped
    networks:
      - postgres

  app:
    image: server:latest
    container_name: app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
