name: Docker Image CI

on:
  push:
    branches: [ "github-action" ]
  pull_request:
    branches: [ "github-action" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build -f Dockerfile.backend --build-arg SERVICE_NAME=cardlist -t lamlance/trello-backend:hai-latest .

    - name: Push the Docker image
      run: docker push lamlance/trello-backend:hai-latest
      
